# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\catdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CatDlg(object):
    def setupUi(self, CatDlg):
        CatDlg.setObjectName("CatDlg")
        CatDlg.resize(400, 172)
        self.gridLayout = QtWidgets.QGridLayout(CatDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.editNick = QtWidgets.QLineEdit(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editNick.setFont(font)
        self.editNick.setObjectName("editNick")
        self.gridLayout.addWidget(self.editNick, 1, 1, 1, 2)
        self.lblAge = QtWidgets.QLabel(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblAge.setFont(font)
        self.lblAge.setObjectName("lblAge")
        self.gridLayout.addWidget(self.lblAge, 3, 0, 1, 1)
        self.btnSave = QtWidgets.QPushButton(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 6, 2, 1, 1)
        self.lblGender = QtWidgets.QLabel(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGender.setFont(font)
        self.lblGender.setObjectName("lblGender")
        self.gridLayout.addWidget(self.lblGender, 4, 0, 1, 1)
        self.lblNick = QtWidgets.QLabel(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblNick.setFont(font)
        self.lblNick.setObjectName("lblNick")
        self.gridLayout.addWidget(self.lblNick, 1, 0, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout.addWidget(self.btnCancel, 6, 1, 1, 1)
        self.rbMale = QtWidgets.QRadioButton(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rbMale.setFont(font)
        self.rbMale.setChecked(True)
        self.rbMale.setObjectName("rbMale")
        self.gridLayout.addWidget(self.rbMale, 4, 1, 1, 1)
        self.editAge = QtWidgets.QSpinBox(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editAge.setFont(font)
        self.editAge.setObjectName("editAge")
        self.gridLayout.addWidget(self.editAge, 3, 1, 1, 1)
        self.rbFemale = QtWidgets.QRadioButton(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rbFemale.setFont(font)
        self.rbFemale.setObjectName("rbFemale")
        self.gridLayout.addWidget(self.rbFemale, 4, 2, 1, 1)
        self.lblBreed = QtWidgets.QLabel(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBreed.setFont(font)
        self.lblBreed.setObjectName("lblBreed")
        self.gridLayout.addWidget(self.lblBreed, 0, 0, 1, 1)
        self.cbBreed = QtWidgets.QComboBox(CatDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbBreed.setFont(font)
        self.cbBreed.setObjectName("cbBreed")
        self.gridLayout.addWidget(self.cbBreed, 0, 1, 1, 2)

        self.retranslateUi(CatDlg)
        QtCore.QMetaObject.connectSlotsByName(CatDlg)

    def retranslateUi(self, CatDlg):
        _translate = QtCore.QCoreApplication.translate
        CatDlg.setWindowTitle(_translate("CatDlg", "Cat"))
        self.lblAge.setText(_translate("CatDlg", "Age"))
        self.btnSave.setText(_translate("CatDlg", "Save"))
        self.lblGender.setText(_translate("CatDlg", "Gender"))
        self.lblNick.setText(_translate("CatDlg", "Nick"))
        self.btnCancel.setText(_translate("CatDlg", "Cancel"))
        self.rbMale.setText(_translate("CatDlg", "Male"))
        self.rbFemale.setText(_translate("CatDlg", "Female"))
        self.lblBreed.setText(_translate("CatDlg", "Breed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CatDlg = QtWidgets.QDialog()
    ui = Ui_CatDlg()
    ui.setupUi(CatDlg)
    CatDlg.show()
    sys.exit(app.exec_())
