# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\imgFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_imgFrame(object):
    def setupUi(self, imgFrame):
        imgFrame.setObjectName("imgFrame")
        imgFrame.resize(614, 448)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(imgFrame.sizePolicy().hasHeightForWidth())
        imgFrame.setSizePolicy(sizePolicy)
        imgFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(imgFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.saPetList = QtWidgets.QScrollArea(imgFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saPetList.sizePolicy().hasHeightForWidth())
        self.saPetList.setSizePolicy(sizePolicy)
        self.saPetList.setMinimumSize(QtCore.QSize(0, 420))
        self.saPetList.setBaseSize(QtCore.QSize(0, 420))
        self.saPetList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.saPetList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.saPetList.setWidgetResizable(True)
        self.saPetList.setObjectName("saPetList")
        self.saWidget = QtWidgets.QWidget()
        self.saWidget.setGeometry(QtCore.QRect(0, 0, 612, 418))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saWidget.sizePolicy().hasHeightForWidth())
        self.saWidget.setSizePolicy(sizePolicy)
        self.saWidget.setBaseSize(QtCore.QSize(0, 0))
        self.saWidget.setObjectName("saWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.saWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imgLayout = QtWidgets.QHBoxLayout()
        self.imgLayout.setSpacing(5)
        self.imgLayout.setObjectName("imgLayout")
        self.img = QtWidgets.QLabel(self.saWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img.sizePolicy().hasHeightForWidth())
        self.img.setSizePolicy(sizePolicy)
        self.img.setBaseSize(QtCore.QSize(400, 400))
        self.img.setObjectName("img")
        self.imgLayout.addWidget(self.img)
        self.horizontalLayout.addLayout(self.imgLayout)
        self.saPetList.setWidget(self.saWidget)
        self.verticalLayout.addWidget(self.saPetList)

        self.retranslateUi(imgFrame)
        QtCore.QMetaObject.connectSlotsByName(imgFrame)

    def retranslateUi(self, imgFrame):
        _translate = QtCore.QCoreApplication.translate
        imgFrame.setWindowTitle(_translate("imgFrame", "Form"))
        self.img.setText(_translate("imgFrame", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    imgFrame = QtWidgets.QWidget()
    ui = Ui_imgFrame()
    ui.setupUi(imgFrame)
    imgFrame.show()
    sys.exit(app.exec_())
