# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\logindialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDlg(object):
    def setupUi(self, LoginDlg):
        LoginDlg.setObjectName("LoginDlg")
        LoginDlg.resize(400, 151)
        font = QtGui.QFont()
        font.setPointSize(12)
        LoginDlg.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(LoginDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.editLogin = QtWidgets.QLineEdit(LoginDlg)
        self.editLogin.setObjectName("editLogin")
        self.gridLayout.addWidget(self.editLogin, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(LoginDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(LoginDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.editPass = QtWidgets.QLineEdit(LoginDlg)
        self.editPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPass.setObjectName("editPass")
        self.gridLayout.addWidget(self.editPass, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(LoginDlg)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnLogin = QtWidgets.QPushButton(LoginDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLogin.sizePolicy().hasHeightForWidth())
        self.btnLogin.setSizePolicy(sizePolicy)
        self.btnLogin.setMinimumSize(QtCore.QSize(0, 0))
        self.btnLogin.setBaseSize(QtCore.QSize(0, 0))
        self.btnLogin.setDefault(True)
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout.addWidget(self.btnLogin)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)

        self.retranslateUi(LoginDlg)
        QtCore.QMetaObject.connectSlotsByName(LoginDlg)

    def retranslateUi(self, LoginDlg):
        _translate = QtCore.QCoreApplication.translate
        LoginDlg.setWindowTitle(_translate("LoginDlg", "Dialog"))
        self.editLogin.setWhatsThis(_translate("LoginDlg", "Input Your login"))
        self.label_2.setText(_translate("LoginDlg", "Login:"))
        self.label.setText(_translate("LoginDlg", "Password"))
        self.btnCancel.setWhatsThis(_translate("LoginDlg", "Click if U afraid and wanna go back"))
        self.btnCancel.setText(_translate("LoginDlg", "Cancel"))
        self.btnLogin.setWhatsThis(_translate("LoginDlg", "Click to login"))
        self.btnLogin.setText(_translate("LoginDlg", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDlg = QtWidgets.QDialog()
    ui = Ui_LoginDlg()
    ui.setupUi(LoginDlg)
    LoginDlg.show()
    sys.exit(app.exec_())
